### PR TITLE
EITI harvester cannot insert dataset

### PR DESCRIPTION
**Pull request by cmovz**
## Why
Harvester errors since 4th of December.

## What
- [x] EITI harvester works as expected 

## Notes
```
Dec 05 08:03:37 02ab42a760ea ecs-eiti-harvester-master-task-15-eiti-harvester-master-container-d6affa9e84e7d82e0000: Dataset eiti-summary-data-table-for-sao-tome-and-principe key: country is different
Dec 05 08:03:37 02ab42a760ea ecs-eiti-harvester-master-task-15-eiti-harvester-master-container-d6affa9e84e7d82e0000: DATASET eiti-summary-data-table-for-sao-tome-and-principe NEEDS UPDATE, UPDATING
Dec 05 08:03:37 02ab42a760ea ecs-eiti-harvester-master-task-15-eiti-harvester-master-container-d6affa9e84e7d82e0000: PATCH DATASET RESULT:
Dec 05 08:03:37 02ab42a760ea ecs-eiti-harvester-master-task-15-eiti-harvester-master-container-d6affa9e84e7d82e0000: {u'help': u'https://www.resourcedata.org/api/3/action/help_show?name=package_patch', u'success': False, u'error': {u'country': [u'unexpected choice "S\xe3o Tom\xe9 and Pr\xedncipe"'], u'__type': u'Validation Error'}}
Dec 05 08:03:37 02ab42a760ea ecs-eiti-harvester-master-task-15-eiti-harvester-master-container-d6affa9e84e7d82e0000: Traceback (most recent call last):
Dec 05 08:03:37 02ab42a760ea ecs-eiti-harvester-master-task-15-eiti-harvester-master-container-d6affa9e84e7d82e0000:   File "./eiti.py", line 173, in <module>
Dec 05 08:03:37 02ab42a760ea ecs-eiti-harvester-master-task-15-eiti-harvester-master-container-d6affa9e84e7d82e0000:     main()
Dec 05 08:03:37 02ab42a760ea ecs-eiti-harvester-master-task-15-eiti-harvester-master-container-d6affa9e84e7d82e0000:   File "./eiti.py", line 170, in main
Dec 05 08:03:37 02ab42a760ea ecs-eiti-harvester-master-task-15-eiti-harvester-master-container-d6affa9e84e7d82e0000:     eiti_import.main()
Dec 05 08:03:37 02ab42a760ea ecs-eiti-harvester-master-task-15-eiti-harvester-master-container-d6affa9e84e7d82e0000:   File "/root/eiti_harvester/eiti_import.py", line 272, in main
Dec 05 08:03:37 02ab42a760ea ecs-eiti-harvester-master-task-15-eiti-harvester-master-container-d6affa9e84e7d82e0000:     import_dataset(d)
Dec 05 08:03:37 02ab42a760ea ecs-eiti-harvester-master-task-15-eiti-harvester-master-container-d6affa9e84e7d82e0000:   File "/root/eiti_harvester/eiti_import.py", line 233, in import_dataset
Dec 05 08:03:37 02ab42a760ea ecs-eiti-harvester-master-task-15-eiti-harvester-master-container-d6affa9e84e7d82e0000:     for resource in dataset['resources']:
Dec 05 08:03:37 02ab42a760ea ecs-eiti-harvester-master-task-15-eiti-harvester-master-container-d6affa9e84e7d82e0000: TypeError: 'NoneType' object has no attribute '__getitem__'
```

### CODE REVIEW

**Comment by adinuca** [comment]
@cmovz , this is the error that occurs now on staging when running the harvester: 
```
nts to Unicode - interpreting them as being unequal
Feb 24 09:17:31 22d1dfb08689 ecs-eiti-harvester-staging-task-6-eiti-harvester-staging-container-bcc2ba85b08f9fe1f101:   if ckan_names.get(countryname):
Feb 24 09:17:31 22d1dfb08689 ecs-eiti-harvester-staging-task-6-eiti-harvester-staging-container-bcc2ba85b08f9fe1f101: UPSERTING DATASET eiti-summary-data-table-for-sao-tome-and-principe
Feb 24 09:17:31 22d1dfb08689 ecs-eiti-harvester-staging-task-6-eiti-harvester-staging-container-bcc2ba85b08f9fe1f101: DATA FROM CKAN (EXISTING):
Feb 24 09:17:31 22d1dfb08689 ecs-eiti-harvester-staging-task-6-eiti-harvester-staging-container-bcc2ba85b08f9fe1f101: {u'owner_org': u'16cecb17-b452-4538-82af-783d4c84cbf1', u'maintainer': u'Anders Pedersen', u'relationships_as_object': [], u'country_iso3': [u'STP'], u'private': False, u'maintainer_email': u'apedersen@resourcegovernance.org', u'num_tags': 0, u'year': [u'2017', u'2016', u'2015'], u'id': u'638f1280-cfa2-45eb-88d1-d24668d6ff5b', u'metadata_created': u'2017-01-28T20:24:41.252001', u'category': [u'Precept 2: Accountability and Transparency'], u'metadata_modified': u'2019-12-03T07:52:11.988935', u'title': u'EITI Summary data table for Sao Tome and Principe', u'state': u'active', u'creator_user_id': u'b6147337-e8b1-4d5d-87b9-0171897afb24', u'type': u'dataset', u'resources': [{u'cache_last_updated': None, u'package_id': u'638f1280-cfa2-45eb-88d1-d24668d6ff5b', u'datastore_active': True, u'id': u'f6f13446-5945-4b2f-818a-53b94f604e96', u'size': 3969, u'state': u'active', u'type': u'file.upload', u'updated': u'2019-12-03', u'hash': u'', u'description': u'', u'format': u'CSV', u'last_modified': u'2017-08-09T14:46:29.419357', u'url_type': u'upload', u'mimetype': u'text/csv', u'cache_url': None, u'name': u'Company payments - Sao Tome and Principe', u'created': u'2017-08-09T14:46:29.577127', u'url': u'https://staging.resourcedata.org/dataset/638f1280-cfa2-45eb-88d1-d24668d6ff5b/resource/f6f13446-5945-4b2f-818a-53b94f604e96/download/company-payments-sao-tome-and-principe.csv', u'mimetype_inner': None, u'position': 0, u'revision_id': u'7d586d65-7df6-49d2-8a39-f2b210f4311d', u'resource_type': None}, {u'cache_last_updated': None, u'package_id': u'638f1280-cfa2-45eb-88d1-d24668d6ff5b', u'datastore_active': True, u'id': u'c1ed8241-42bb-4595-bf27-86ebc355e5f4', u'size': 10885, u'state': u'active', u'type': u'file.upload', u'updated': u'2019-12-03', u'hash': u'', u'description': u'', u'format': u'CSV', u'last_modified': u'2017-08-09T14:46:32.022731', u'url_type': u'upload', u'mimetype': u'text/csv', u'cache_url': None, u'name': u'Revenues received by government agencies - Sao Tome and Principe', u'created': u'2017-08-09T14:46:32.329157', u'url': u'https://staging.resourcedata.org/dataset/638f1280-cfa2-45eb-88d1-d24668d6ff5b/resource/c1ed8241-42bb-4595-bf27-86ebc355e5f4/download/revenues-received-by-government-agencies-sao-tome-and-principe.csv', u'mimetype_inner': None, u'position': 1, u'revision_id': u'7d586d65-7df6-49d2-8a39-f2b210f4311d', u'resource_type': None}], u'num_resources': 2, u'tags': [], u'groups': [], u'license_id': u'cc-by', u'relationships_as_subject': [], u'name': u'eiti-summary-data-table-for-sao-tome-and-principe', u'isopen': True, u'url': u'https://eiti.org/api/v1.0/summary_data', u'country': [u'Sao Tome and Principe'], u'notes': u'\n    The data is published using the Summary Data Template, Version 1.1 as of 05 March 2015.\n\nAccording to the EITI Standard 5.3.b: "Summary data from each EITI Report should be submitted electronically to the International Secretariat according to the standardised reporting format provided by the International Secretariat" This template should be completed in full and submitted by email by the national secretariat to the International EITI Secretariat following the publication of the report. The data will be used to populate the global EITI data repository, available on the international EITI website.\n\nNB: The data available on ResourceData is republished from the EITI API and covers one section of the Summary Data, Part 3 which is comprised of data on government revenues per revenue stream and company.\n\nNotes for consideration:\n\nDisclaimer: The EITI Secretariat advice that users consult the original reports for detailed information. Where figures are not available in US dollars, the annual average exchange rate is used. Any questions regarding the data collection and Summary Data methodology can be directed to the EITI Secretariat: data@eiti.org or by visiting [eiti.org/summary-data](http://eiti.org/summary-data)\n        ', u'license_title': u'Creative Commons Attribution', u'qa': {u'openness_score_reason': u'One of the resource formats is 3-star data - machine-readable data in an open format.', u'openness_score': 3}, u'license_url': u'http://www.opendefinition.org/licenses/cc-by', u'organization': {u'description': u'The Extractive Industries Transparency Initiative (EITI) is a global Standard to promote the open and accountable management of natural resources.\r\n\r\nThe Standard seeks to addresses the key governance issues of the oil, gas and mining sectors.', u'created': u'2017-01-26T09:44:04.790954', u'title': u'Extractive Industries Transparency Initiative (EITI)', u'name': u'eiti', u'is_organization': True, u'state': u'active', u'image_url': u'https://eiti.org/sites/all/themes/eiti/logo.svg', u'revision_id': u'0d7b3b86-fb78-47c2-9bdb-ca0086c012a4', u'type': u'organization', u'id': u'16cecb17-b452-4538-82af-783d4c84cbf1', u'approval_status': u'approved'}, u'revision_id': u'9fd4ad32-3944-40c9-b802-325e1de6c9c1'}
Feb 24 09:17:31 22d1dfb08689 ecs-eiti-harvester-staging-task-6-eiti-harvester-staging-container-bcc2ba85b08f9fe1f101: Dataset eiti-summary-data-table-for-sao-tome-and-principe key: country is different
Feb 24 09:17:31 22d1dfb08689 ecs-eiti-harvester-staging-task-6-eiti-harvester-staging-container-bcc2ba85b08f9fe1f101: DATASET eiti-summary-data-table-for-sao-tome-and-principe NEEDS UPDATE, UPDATING
Feb 24 09:17:31 22d1dfb08689 ecs-eiti-harvester-staging-task-6-eiti-harvester-staging-container-bcc2ba85b08f9fe1f101: PATCH DATASET RESULT:
Feb 24 09:17:31 22d1dfb08689 ecs-eiti-harvester-staging-task-6-eiti-harvester-staging-container-bcc2ba85b08f9fe1f101: {u'help': u'https://staging.resourcedata.org/api/3/action/help_show?name=package_patch', u'success': False, u'error': {u'country': [u'unexpected choice "S\xe3o Tom\xe9 and Pr\xedncipe"'], u'__type': u'Validation Error'}}
Feb 24 09:17:31 22d1dfb08689 ecs-eiti-harvester-staging-task-6-eiti-harvester-staging-container-bcc2ba85b08f9fe1f101: Traceback (most recent call last):
Feb 24 09:17:31 22d1dfb08689 ecs-eiti-harvester-staging-task-6-eiti-harvester-staging-container-bcc2ba85b08f9fe1f101:   File "./eiti.py", line 173, in <module>
Feb 24 09:17:31 22d1dfb08689 ecs-eiti-harvester-staging-task-6-eiti-harvester-staging-container-bcc2ba85b08f9fe1f101:     main()
Feb 24 09:17:31 22d1dfb08689 ecs-eiti-harvester-staging-task-6-eiti-harvester-staging-container-bcc2ba85b08f9fe1f101:   File "./eiti.py", line 170, in main
Feb 24 09:17:31 22d1dfb08689 ecs-eiti-harvester-staging-task-6-eiti-harvester-staging-container-bcc2ba85b08f9fe1f101:     eiti_import.main()
Feb 24 09:17:31 22d1dfb08689 ecs-eiti-harvester-staging-task-6-eiti-harvester-staging-container-bcc2ba85b08f9fe1f101:   File "/root/eiti_harvester/eiti_import.py", line 273, in main
Feb 24 09:17:31 22d1dfb08689 ecs-eiti-harvester-staging-task-6-eiti-harvester-staging-container-bcc2ba85b08f9fe1f101:     import_dataset(d)
Feb 24 09:17:31 22d1dfb08689 ecs-eiti-harvester-staging-task-6-eiti-harvester-staging-container-bcc2ba85b08f9fe1f101:   File "/root/eiti_harvester/eiti_import.py", line 234, in import_dataset
Feb 24 09:17:31 22d1dfb08689 ecs-eiti-harvester-staging-task-6-eiti-harvester-staging-container-bcc2ba85b08f9fe1f101:     for resource in dataset['resources']:
Feb 24 09:17:31 22d1dfb08689 ecs-eiti-harvester-staging-task-6-eiti-harvester-staging-container-bcc2ba85b08f9fe1f101: TypeError: 'NoneType' object has no attribute '__getitem__'
Feb 24 09:17:31 ip-10-0-0-124 ecs-agent: 2020-02-24T07:17:31Z [INFO] Task [arn:aws:ecs:us-east-1:877912432675:task/255d6e24-f817-4b36-bc2f-54bfa5a98570]: recording execution stopped time. 
```
https://papertrailapp.com/groups/3881793/events?q=%20eiti-harvester-staging

Please solve this as well.

**Comment by cmovz** [comment]
Now I'm running into the following problem:

```
Traceback (most recent call last):
  File "harvesters/eiti/scripts/eiti.py", line 174, in <module>
    main()
  File "harvesters/eiti/scripts/eiti.py", line 158, in main
    gather_csvs(country)
  File "harvesters/eiti/scripts/eiti.py", line 96, in gather_csvs
    resp = session.get(url)
  File "/Users/douglas/Library/Python/2.7/lib/python/site-packages/requests/sessions.py", line 546, in get
    return self.request('GET', url, **kwargs)
  File "/Users/douglas/Library/Python/2.7/lib/python/site-packages/requests/sessions.py", line 519, in request
    prep = self.prepare_request(req)
  File "/Users/douglas/Library/Python/2.7/lib/python/site-packages/requests/sessions.py", line 462, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "/Users/douglas/Library/Python/2.7/lib/python/site-packages/requests/models.py", line 313, in prepare
    self.prepare_url(url, params)
  File "/Users/douglas/Library/Python/2.7/lib/python/site-packages/requests/models.py", line 387, in prepare_url
    raise MissingSchema(error)
requests.exceptions.MissingSchema: Invalid URL '': No schema supplied. Perhaps you meant http://?
```

URL is empty:
```
{u'mimetype': None, u'cache_url': None, u'hash': u'', u'description': u'', u'last_modified': None, u'format': u'CSV', u'url': u'', u'type': u'file.upload', u'cache_last_updated': None, u'state': u'active', u'created': u'2020-02-14T12:22:33.836158', u'package_id': u'638f1280-cfa2-45eb-88d1-d24668d6ff5b', u'mimetype_inner': None, u'url_type': None, u'position': 2, u'revision_id': u'd94c42a4-b9c9-42a2-b354-9865e25d0520', u'size': None, u'datastore_active': False, u'id': u'c4b2884e-7bf1-4c6a-a559-8748696cbc70', u'resource_type': None, u'name': u'Company payments - S\xe3o Tom\xe9 and Pr\xedncipe'}
```

**Comment by cmovz** [comment]
I can't reproduce the staging error

**Comment by adinuca** [comment]
@cmovz , I will pick this up. Thank you for your help.

**Pull request merged**
